### ISSUE TITLE
curris band

### ISSUE THREAD

**Issue by LiaoChengkk** [zhuqinghe/RS-Haze#2]
请问怎么获得curris band数据？

**Comment by zhuqinghe** [comment]
1、需要您下载的数据集中的原始多光谱图像数据中就包含cirrus通道，是否包含cirrus通道和遥感卫星的传感器相关，需要查阅相关卫星传感器的数据手册。一般Landsat7、8系列都包含cirrus通道。
2、我先close了，有问题请再open。
